// File generated by FlutterFire CLI - PLACEHOLDER
// This is a placeholder file. Run `flutterfire configure` to generate the real file.
// DO NOT COMMIT this file to version control.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRBk10Z6_dAo-wP3caETpeKSUIKcu2m8',
    appId: '1:142135278951:web:4e7e7b7a8963f34f2003c2',
    messagingSenderId: '142135278951',
    projectId: 'sub-guard-cb8f5',
    authDomain: 'sub-guard-cb8f5.firebaseapp.com',
    storageBucket: 'sub-guard-cb8f5.firebasestorage.app',
    measurementId: 'G-S5C2T6EGTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuV_El_24gueBP3yOSCrDXO-rH8tAaKZw',
    appId: '1:142135278951:android:f917221539295ba82003c2',
    messagingSenderId: '142135278951',
    projectId: 'sub-guard-cb8f5',
    storageBucket: 'sub-guard-cb8f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjq4d6TUSud4fcAeCYafJ7O7jNuiRdpw',
    appId: '1:142135278951:ios:d829aa059a718d9d2003c2',
    messagingSenderId: '142135278951',
    projectId: 'sub-guard-cb8f5',
    storageBucket: 'sub-guard-cb8f5.firebasestorage.app',
    iosBundleId: 'com.example.subGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUjq4d6TUSud4fcAeCYafJ7O7jNuiRdpw',
    appId: '1:142135278951:ios:d829aa059a718d9d2003c2',
    messagingSenderId: '142135278951',
    projectId: 'sub-guard-cb8f5',
    storageBucket: 'sub-guard-cb8f5.firebasestorage.app',
    iosBundleId: 'com.example.subGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVRBk10Z6_dAo-wP3caETpeKSUIKcu2m8',
    appId: '1:142135278951:web:55dbf6a8a18c82d92003c2',
    messagingSenderId: '142135278951',
    projectId: 'sub-guard-cb8f5',
    authDomain: 'sub-guard-cb8f5.firebaseapp.com',
    storageBucket: 'sub-guard-cb8f5.firebasestorage.app',
    measurementId: 'G-P8B3S05LMQ',
  );

}