import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

import 'core/database/isar_provider.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/logger.dart';
import 'features/auth/data/models/user_model.dart';
import 'features/notifications/data/models/notification_model.dart';
import 'features/subscriptions/data/models/subscription_model.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Set system UI overlay style
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  // Set preferred orientations
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    logger.info('✅ Firebase initialized successfully');
  } catch (e) {
    logger.error('❌ Firebase initialization failed: $e');
    // Note: App will still run but Firebase features won't work
  }

  // Initialize Isar database
  late Isar isar;
  try {
    final dir = await getApplicationDocumentsDirectory();
    isar = await Isar.open(
      [
        UserModelSchema,
        SubscriptionModelSchema,
        NotificationModelSchema,
        NotificationSettingsModelSchema,
      ],
      directory: dir.path,
      name: 'subguard_db',
    );
    logger.info('✅ Isar database initialized');
  } catch (e) {
    logger.error('❌ Isar initialization failed: $e');
    rethrow; // Isar is critical, so we rethrow
  }

  // Initialize logger
  logger.info('🚀 SubGuard App Starting...');

  runApp(
    ProviderScope(
      overrides: [
        // Override Isar provider with actual instance
        isarProvider.overrideWithValue(isar),
      ],
      child: const SubGuardApp(),
    ),
  );
}

class SubGuardApp extends ConsumerWidget {
  const SubGuardApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'SubGuard - Subscription Tracker',
      debugShowCheckedModeBanner: false,

      // Theme
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode:
          ThemeMode.light, // TODO: Make this dynamic based on user preference
      // Router
      routerConfig: router,
    );
  }
}
