import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/database/hive_provider.dart';
import 'core/database/hive_service.dart';
import 'core/notifications/notification_service.dart';
import 'core/router/app_router.dart';
import 'core/security/app_lock_gate.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/logger.dart';
import 'features/notifications/presentation/providers/notification_providers.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Set system UI overlay style for Edge-to-Edge
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  // Set preferred orientations
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Firebase (optional - app will work without it)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    logger.info('✅ Firebase initialized successfully');
  } catch (e) {
    logger.warning('⚠️ Firebase initialization skipped: $e');
    logger.info('App will run without Firebase features (sync, remote backup)');
    // Continue without Firebase - local features will still work
  }

  // Initialize Hive database
  try {
    await hiveService.init();
    logger.info('✅ Hive database initialized');
  } catch (e, stackTrace) {
    logger.error('❌ Hive initialization failed: $e');
    logger.error('Stack trace: $stackTrace');
    rethrow;
  }

  // Initialize Notification Service
  final notificationPlugin = FlutterLocalNotificationsPlugin();
  final notificationService = NotificationService(notificationPlugin);
  try {
    await notificationService.initialize();
    logger.info('✅ Notification service initialized');
  } catch (e, stackTrace) {
    logger.warning(
      '⚠️ Notification service initialization failed: $e\n$stackTrace',
    );
  }

  // Initialize logger
  logger.info('🚀 SubGuard App Starting...');

  runApp(
    ProviderScope(
      overrides: [
        hiveServiceProvider.overrideWithValue(hiveService),
        notificationServiceProvider.overrideWithValue(notificationService),
      ],
      child: const SubGuardApp(),
    ),
  );
}

class SubGuardApp extends ConsumerWidget {
  const SubGuardApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'SubGuard - Subscription Tracker',
      debugShowCheckedModeBanner: false,

      // Theme
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode:
          ThemeMode.light, // TODO: Make this dynamic based on user preference
      // Router
      routerConfig: router,
      builder: (context, child) {
        return AppLockGate(child: child ?? const SizedBox.shrink());
      },
    );
  }
}
